config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'ideas' => 'static_pages#ideas'

  get 'about' => 'static_pages#about'

  get 'random' => 'static_pages#random'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ideas#index'

  resources :ideas
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def index
		@ideas = Idea.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
	end

	def create
		@idea = Idea.create(idea_params)
		if @idea.valid?
	    	flash[:success] = "Your idea has been posted!"
	  	else
	    	flash[:alert] = "Woops! Looks like there has been an error!"
	  	end
		redirect_to root_path
	end

	# def edit
	# 	@idea = Idea.find(params[:id])
	# end

	def update
	  @idea = Idea.find(params[:id])
	  if @idea.update(idea_params)
	  	flash[:success] = "The idea has been updated!"
	    redirect_to root_path
	  else
	  	flash[:alert] = "Woops! Looks like there has been an error!"
	    redirect_to edit_idea_path(params[:id])
	  end
	end

	# def destroy
	#   @idea = Idea.find(params[:id])
	#   @idea.destroy
	#   flash[:success] = "The idea was successfully deleted!"
	#   redirect_to root_path
	# end

	private

	def idea_params
	  params.require(:idea).permit(:description, :author)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about

  	end

  	def random
  		@idea = Idea.order("RANDOM()").first
  	end

  	def ideas
  		@ideas = Idea.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<button type="button" class="btn btn-primary btn-lg mp-btn" data-toggle="modal" data-target="#myModal">
  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
 Post an Idea
</button>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Add New Idea</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for Idea.new do |f| %>
          <%= f.input :description %>
          <%= f.input :author %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>

      <% end %>

    </div>
  </div>
</div>

<% @ideas.each do |idea| %>
<div class="break"></div>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= idea.description %></p>
        <small>by <%= idea.author %></small>
      </blockquote> 
      
      <!--
      <br>
      <%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
      <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success'%>
      -->
    </div>
  </div>
<% end %>

<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator - Discover and Share Ideas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans:300,400,600,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- favicon -->
    <%= favicon_link_tag %>
    
    <!--  Mobile Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

  <body>

    <div id="wrap">
      <%= render 'shared/nav' %>

      <hr style="
    margin-left: 1%;
    margin-right: 1%;
"><!-- for horizontal line after nav bar -->

      <div class = "container">
        <%= render 'shared/flash_messages' %>
        <%= yield %>                 
      </div>

    </div><!-- wrap -->

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center">
  <div class="container">
    <div class = "row">
    	<div class = "col-xs-12 col-md-4">
    		<h4>Contact</h4>
    		<p><a href="mailto:poudelmadhav143@gmail.com">poudelmadhav143@gmail.com</a></p>
    	</div>
    	<div class = "col-xs-12 col-md-4">
    		<h4>Find Me</h4>
    		<div class="social-buttons">
	    		<a href = "http://facebook.com/poudelmadhav143" title="Facebook"><i class="fa fa-facebook-official social" ></i></a>
	    		<a href = "http://twitter.com/poudelmadhav143" title="Twitter"><i class="fa fa-twitter-square social" ></i></a>
	    		<a href = "https://np.linkedin.com/in/madhav-paudel-8b0469135" title="LinkedIn"><i class="fa fa-linkedin-square social" ></i></a>
	    	</div>
    	</div>
    	<div class = "col-xs-12 col-md-4">
    		<h4>&copy; <a href="http://poudelmadhav.com.np">Madhav Paudel</a> <%= Date.today.year %></h4>
    		<p>All Rights Reserved.</p>
    	</div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/">Madhav's Ideator</a>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'All Ideas', ideas_path %></li>
      <li><%= link_to 'Inspire Me', random_path %></li>
      <li><%= link_to 'About', about_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->

</div><!-- navbar-header -->

app/views/static_pages/about.html.erb
<h1>About</h1>

<h4>Share your ideas with the world and find others.</h4>

<p>
  I am student of Computer Science and Information Technology at Tribhuvan University. I love programming and technology field. I want to become a successful programmer and a web developer.
</p>

<p>
  Here, you can share your ideas with the world. Enjoy!!!
</p>

app/views/static_pages/ideas.html.erb
<h1>All Ideas</h1>
<% @ideas.each do |idea| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= idea.description %></p>
        <small>by <%= idea.author %></small>
      </blockquote> 
    </div>
  </div>
<% end %>

<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
  <%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>
    
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= @idea.description %></p>
        <small>by <%= @idea.author %></small>
      </blockquote>
      <!-- 
      <br>

      <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
      </div>
      -->
    </div>
  </div>
  <% else %>
  <h4>No ideas have been shared. Add one <%= link_to 'here', root_path %></h4>

<% end %>